dist: xenial
language: bash

branches:
  only:
    - master

notifications:
  email: false

addons:
  apt:
    packages:
      - gcc
      - g++
      - make
      - automake
      - autoconf
      - libtool
      - git
      - ccache
      - file
      - patch
      - curl
      - quilt
      - gawk
      - time
      - fakeroot
      - gettext
      - pkg-config
      - python2.7-minimal
      - libssl-dev
      - libncurses5-dev
      - zlib1g-dev
      - bzip2
      - xz-utils
      - unzip

env:
  matrix:
    - SDK_URL=https://downloads.openwrt.org/releases/18.06.4/targets/ar71xx/generic/openwrt-sdk-18.06.4-ar71xx-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
    - SDK_URL=https://downloads.openwrt.org/releases/18.06.4/targets/ar71xx/tiny/openwrt-sdk-18.06.4-ar71xx-tiny_gcc-7.3.0_musl.Linux-x86_64.tar.xz
    - SDK_URL=https://downloads.openwrt.org/releases/18.06.4/targets/ramips/mt7620/openwrt-sdk-18.06.4-ramips-mt7620_gcc-7.3.0_musl.Linux-x86_64.tar.xz
    - SDK_URL=https://downloads.openwrt.org/releases/18.06.4/targets/x86/64/openwrt-sdk-18.06.4-x86-64_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  global:
    - secure: "iq8eFoGpKiBlBC8K3Psw62sjGT3PqqSYlIdRUM1dPEDdpDYR0iOz0qoNq6AseUuWWs02+Kck+RcYCxXiLk2DLwKVD5yyNqUab6hR4+9mm7DszXSb7CYIxLMMzFcS1IY4ompd0ljUFi/wPdMuYxm6gNKnAlda9V+8YtH3nn7vYSPOb3mmVwzMZR0wR2752Pem4b5Wa1JbnBL13NrXTXcuRRTtWYFy0lb4ZXE1jB++pufn93Xxhg0RjQ0HYoUg+xZZf+uNh3dP5pbYreasrx3oKfjTPtDtRlU7hF3nPE2iqenwcW3WT79W0LVLgBsVA41zyzhHmSGOThm/4l5/yXHK0mGHkq0sAaG/K/sUZ4Pa3lOftsgo+4pRP3uY+bOn2JPPszftBimKhVMifRwbunlstC6A7tDfTXKSScZZOjy+IPilc2tdIJBxZqWMeCtP6FoxNDubw59SSSUvbK755WVtFJVsFMN8OtjX8CZkAtHwVCRropt2kz61kO2dR9NjW4YfIMX/bHnAVU6CLU1/l+RlDplx7oW6s80RjLNTAgdhhW/mPE9rh7jKXibK3vpqn6q3ka5dazM6RiTFzgSQGTcwMHvNFSHP5hn1eURmtngAt0NWJ48BrPx6BvIgcvkJF+JoXmiPkQvO+tIct3wMW+ZNxriPYUv3ESmyh+i62ccw6qg="
    - TZ: "Asia/Taipei"

install:
  - git clone --single-branch -b master https://github.com/openwrt-dev/po2lmo.git
  - cd po2lmo
  - make && sudo make install && make clean
  - cd ..
  - rm -rf po2lmo

before_script:
  # export TARGET=$(sed -n 's/.*openwrt-sdk-[0-9.]*-\?\(\w*-\w*\).*_gcc.*/\1/p' <<< $SDK_URL)
  # export TARGET=$(sed -n 's/.*[lede,openwrt]-sdk-[0-9.]*[\-rc\d-]*-\(\w*\).*_gcc.*/\1/p' <<< $SDK_URL)
  - export TARGET=$(sed -n 's/.*openwrt-sdk-[0-9.]*-\(\w*-\w*\).*_gcc.*/\1/p' <<< $SDK_URL)

script:
  - ./build.sh

deploy:
  provider: pages
  local-dir: release
  target-branch: ${TARGET}
  keep-history: true
  skip-cleanup: true
  github-token: ${GITHUB_TOKEN}
  on:
    branch: master
