dist: xenial
language: c
cache: ccache

branches:
  only:
    - master

notifications:
  email: false

addons:
  apt:
    packages:
      - gcc
      - g++
      - make
      - automake
      - autoconf
      - libtool
      - git
      - ccache
      - file
      - patch
      - curl
      - quilt
      - gawk
      - fakeroot
      - gettext
      - pkg-config
      - python2.7-minimal
      - zlib1g-dev
      - libssl-dev
      - libncurses5-dev
      - bzip2
      - xz-utils
      - unzip
      - time

env:
  matrix:
    - SDK_URL=https://downloads.openwrt.org/releases/18.06.1/targets/ar71xx/generic/openwrt-sdk-18.06.1-ar71xx-generic_gcc-7.3.0_musl.Linux-x86_64.tar.xz
    - SDK_URL=https://downloads.openwrt.org/releases/18.06.1/targets/ramips/mt7620/openwrt-sdk-18.06.1-ramips-mt7620_gcc-7.3.0_musl.Linux-x86_64.tar.xz
    - SDK_URL=https://downloads.openwrt.org/releases/18.06.1/targets/x86/64/openwrt-sdk-18.06.1-x86-64_gcc-7.3.0_musl.Linux-x86_64.tar.xz
  global:
    - secure: "q6XJxel6ViwCx10LgW9rbvwhMpb+794OjzYCKZ0QRGQbeQdTV6L6MYDTqQZARvpXM6fn9cSmiDF5qSBkVsOabVcShh6x4N3JTYegMhDeQ9yo/BpNWMTsSvA9LAEiK83Tcs31GXPbAEr0KEoy4rA1RFwhO2AdL/E1qEpstfLOMCixXk8rZ/V5k0duJzwzytj567fLRzLm30jYZ91E/yyClUdzhh2xPGP0lEN7Kp9P5vdLlUY56yGUpyd2X5PeKSJzU2r7oEgbHPLp+xX1iPGxN7ZeqGdweB/zClSOG58wVjMLg7eaFwbz+18g/kdRJTO+RkAqX1OyoCmH8ZsnXlXR0o29radRy43qXy0sASZO7vJzP7GD6Dt8xJUOYQZ4cOcNfW0LdSRYrBQfc7O5mQ5D+2uFJAClKX72ZnuNLLISLqScj7mQUym2TULcdkYVwjJhewvuYQdLvWwpW2KzQR48VrqWoc9V03Spu6hamDmcW0qvOGe+ftsgjPjKYVPEz6cZ2KN+ZqR+DqfGbk9+vmgVBrgrLUfmuuSI8limiHYwZT1OtEH+XmeeF9ZGSFL/m1CcMO2dlBP/TfugSR5KUrrEaCLnbIRC+GewadPNmGAxH+HNRSOVcG2FrRWLtV7KW4usPlBNhhch8IxufyGOcjgcOAgNEQyIWU6fcSITXwO0GJQ="
    - TZ: "Asia/Shanghai"

install:
  - git clone https://github.com/openwrt-dev/po2lmo.git
  - pushd po2lmo
  - make && sudo make install && make clean
  - popd
  - rm -rf po2lmo

before_script:
  - export ARCH=$(basename $SDK_URL | sed -n 's/openwrt-sdk-[0-9.]*-\(\w*-\w*\).*_gcc.*/\1/p')

script:
  - bash compile.sh

deploy:
  provider: pages
  local-dir: release
  target-branch: ${ARCH}
  keep-history: true
  skip-cleanup: true
  github-token: ${GITHUB_TOKEN}
  on:
    branch: master
